<script setup lang="ts">
import { ShieldMinus, ShieldPlus } from 'lucide-vue-next'
const { api } = useApi(); const { show } = useToast(); const selected = ref('')
const { data: admins, refresh: refreshAdmins } = await useAsyncData('admin-admins', () => api<any>('/v1/platform-admin/admins'))
const { data: users, refresh: refreshUsers } = await useAsyncData('admin-users-for-admins', () => api<any>('/v1/platform-admin/users'))
const candidates = computed(() => (users.value?.items || []).filter((item: any) => item.status === 'active' && item.email_verified && !item.is_platform_admin))
async function grant() { if (!selected.value) return; await api(`/v1/platform-admin/admins/${selected.value}`, { method: 'POST' }); selected.value = ''; await Promise.all([refreshAdmins(), refreshUsers()]); show('Administrator added', 'Their current sessions were invalidated for role refresh.', 'success') }
async function revoke(item: any) { try { await api(`/v1/platform-admin/admins/${item.id}`, { method: 'DELETE' }); await Promise.all([refreshAdmins(), refreshUsers()]); show('Administrator removed', item.email, 'success') } catch (error: any) { show('Could not remove administrator', error.message, 'error') } }
</script>
<template><div><UiPageHeader eyebrow="Access control" title="Administrators" description="Grant and revoke platform-wide administration separately from customer workspace roles." /><UiAppCard class="grant-card"><div><strong>Add administrator</strong><small>Only active, verified users are eligible.</small></div><select v-model="selected"><option value="">Select a user…</option><option v-for="item in candidates" :key="item.id" :value="item.id">{{ item.email }} — {{ item.display_name }}</option></select><button class="button button--primary button--small" :disabled="!selected" @click="grant"><ShieldPlus :size="15" /> Grant access</button></UiAppCard><div class="admin-list"><UiAppCard v-for="item in admins?.items || []" :key="item.id"><div><span>{{ item.display_name?.slice(0,1)?.toUpperCase() }}</span><p><strong>{{ item.display_name }}</strong><small>{{ item.email }}</small></p></div><p><small>Added account</small><strong>{{ new Date(item.created_at).toLocaleDateString() }}</strong></p><button class="button button--small" @click="revoke(item)"><ShieldMinus :size="14" /> Revoke</button></UiAppCard></div></div></template>
<style scoped>.grant-card{display:grid;grid-template-columns:1fr minmax(260px,420px) auto;gap:12px;align-items:center;margin-bottom:14px}.grant-card>div{display:grid;gap:3px}.grant-card strong{font-size:11px}.grant-card small{font-size:8px;color:var(--muted)}.grant-card select{border:1px solid var(--border);border-radius:9px;padding:9px;font-size:9px}.admin-list{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:12px}.admin-list :deep(.app-card){display:grid;grid-template-columns:1fr auto;gap:12px;align-items:center}.admin-list :deep(.app-card)>div{display:flex;align-items:center;gap:10px}.admin-list :deep(.app-card)>div>span{width:36px;height:36px;border-radius:10px;background:#f3e4f6;color:#852798;display:grid;place-items:center;font-weight:900}.admin-list p{display:grid;margin:0;gap:2px}.admin-list p strong{font-size:10px}.admin-list p small{font-size:8px;color:var(--muted)}.admin-list button{grid-column:1/-1}@media(max-width:800px){.grant-card{grid-template-columns:1fr}}</style>
