<script setup lang="ts">
import { BadgeDollarSign, Gift, Save, ShieldCheck, Users } from 'lucide-vue-next'

const { api } = useApi()
const { show } = useToast()
const tab = ref<'users' | 'promos' | 'pricing'>('users')
const query = ref('')
const creditAmounts = reactive<Record<string, number>>({})
const promoForm = reactive({ code: '', kind: 'ai_tokens', credit_tokens: 1000, subscription_days: 0, max_redemptions: 1 })
const createdCode = ref('')

const { data: overview, refresh: refreshOverview } = await useAsyncData('admin-overview', () => api<any>('/v1/platform-admin/overview'))
const { data: users, refresh: refreshUsers } = await useAsyncData('admin-users', () => api<any>('/v1/platform-admin/users'))
const { data: promos, refresh: refreshPromos } = await useAsyncData('admin-promos', () => api<any>('/v1/platform-admin/promo-codes'))
const { data: pricing, refresh: refreshPricing } = await useAsyncData('admin-pricing', () => api<any>('/v1/platform-admin/pricing'))

const filteredUsers = computed(() => (users.value?.items || []).filter((item: any) => `${item.email} ${item.display_name} ${item.organization_name}`.toLowerCase().includes(query.value.toLowerCase())))

async function setStatus(item: any, status: string) { await api(`/v1/platform-admin/users/${item.id}`, { method: 'PATCH', body: { status } }); await refreshUsers(); show('User updated', `${item.email} is now ${status}.`, 'success') }
async function adjust(item: any) { const amount = Number(creditAmounts[item.id] || 0); if (!amount) return; await api(`/v1/platform-admin/users/${item.id}/credits`, { method: 'POST', body: { amount_tokens: amount, description: 'Manual platform admin adjustment' } }); creditAmounts[item.id] = 0; await Promise.all([refreshUsers(), refreshOverview()]); show('Balance updated', `${amount > 0 ? '+' : ''}${amount} tokens applied.`, 'success') }
async function createPromo() { const result = await api<any>('/v1/platform-admin/promo-codes', { method: 'POST', body: promoForm }); createdCode.value = result.code; await refreshPromos(); show('Promo created', 'Copy the code from the highlighted field.', 'success') }
async function disablePromo(item: any) { await api(`/v1/platform-admin/promo-codes/${item.id}`, { method: 'PATCH', body: { is_active: !item.is_active } }); await refreshPromos() }
async function savePrice(item: any) { await api(`/v1/platform-admin/pricing/${item.feature_key}`, { method: 'PATCH', body: { provider_cost_usd: Number(item.provider_cost_usd), charge_tokens: Number(item.charge_tokens), margin_percent: Number(item.margin_percent), is_active: item.is_active } }); await refreshPricing(); show('Price saved', item.label, 'success') }
</script>

<template>
  <div>
    <UiPageHeader eyebrow="Internal operations" title="Platform admin" description="Users, AI economics and promotional access across Framewise."><span class="admin-lock"><ShieldCheck :size="14" /> Platform administrator</span></UiPageHeader>
    <div class="metric-grid"><UiAppCard class="metric-card"><div class="metric-card__head"><span class="metric-card__icon metric-card__icon--purple"><Users :size="17" /></span><span>Users</span></div><strong>{{ overview?.users?.total || 0 }}</strong><small>{{ overview?.users?.active || 0 }} active</small></UiAppCard><UiAppCard class="metric-card"><div class="metric-card__head"><span class="metric-card__icon metric-card__icon--green"><BadgeDollarSign :size="17" /></span><span>Deposited</span></div><strong>${{ Number(overview?.money?.deposited_usd || 0).toFixed(2) }}</strong><small>Recorded top-ups</small></UiAppCard><UiAppCard class="metric-card"><div class="metric-card__head"><span class="metric-card__icon"><Gift :size="17" /></span><span>AI usage</span></div><strong>{{ Number(overview?.tokens?.spent || 0).toLocaleString() }}</strong><small>tokens spent</small></UiAppCard></div>
    <div class="admin-tabs"><button :class="{active:tab==='users'}" @click="tab='users'">Users</button><button :class="{active:tab==='promos'}" @click="tab='promos'">Promo codes</button><button :class="{active:tab==='pricing'}" @click="tab='pricing'">Pricing & margin</button></div>
    <UiAppCard v-if="tab==='users'"><div class="section-heading"><div><h2>User management</h2><p>Account status, workspace and AI token balance</p></div><input v-model="query" class="admin-search" placeholder="Search users…"></div><div class="table-scroll"><table class="admin-table"><thead><tr><th>User</th><th>Workspace</th><th>Status</th><th>Balance</th><th>Credit adjustment</th><th></th></tr></thead><tbody><tr v-for="item in filteredUsers" :key="item.id"><td><strong>{{ item.display_name }}</strong><small>{{ item.email }}</small></td><td><strong>{{ item.organization_name || '—' }}</strong><small>{{ item.role || '—' }}</small></td><td><UiStatusBadge :status="item.status" /></td><td>{{ Number(item.balance_tokens).toLocaleString() }}</td><td><div class="inline-action"><input v-model.number="creditAmounts[item.id]" type="number" placeholder="± tokens"><button class="button button--small" @click="adjust(item)">Apply</button></div></td><td><button class="button button--small" @click="setStatus(item,item.status==='blocked'?'active':'blocked')">{{ item.status==='blocked'?'Unblock':'Block' }}</button></td></tr></tbody></table></div></UiAppCard>
    <div v-else-if="tab==='promos'" class="admin-columns"><UiAppCard><div class="section-heading"><div><h2>Create promo code</h2><p>AI tokens, subscription time, or both</p></div><Gift :size="18" /></div><form class="admin-form" @submit.prevent="createPromo"><label>Custom code<input v-model="promoForm.code" placeholder="Leave blank to generate"></label><label>Benefit<select v-model="promoForm.kind"><option value="ai_tokens">AI tokens</option><option value="subscription">Subscription</option><option value="bundle">Bundle</option></select></label><label>AI tokens<input v-model.number="promoForm.credit_tokens" type="number" min="0"></label><label>Subscription days<input v-model.number="promoForm.subscription_days" type="number" min="0"></label><label>Maximum redemptions<input v-model.number="promoForm.max_redemptions" type="number" min="1"></label><button class="button button--primary">Create code</button><div v-if="createdCode" class="created-code">{{ createdCode }}</div></form></UiAppCard><UiAppCard><div class="section-heading"><div><h2>Existing codes</h2><p>Only a prefix is retained after creation</p></div></div><div class="promo-list"><div v-for="item in promos?.items || []" :key="item.id"><span><strong>{{ item.code }}</strong><small>{{ item.credit_tokens }} tokens · {{ item.subscription_days }} days · {{ item.redemption_count }}/{{ item.max_redemptions || '∞' }}</small></span><button class="button button--small" @click="disablePromo(item)">{{ item.is_active ? 'Disable' : 'Enable' }}</button></div></div></UiAppCard></div>
    <UiAppCard v-else><div class="section-heading"><div><h2>AI function pricing</h2><p>Provider cost, customer token charge and target margin</p></div><BadgeDollarSign :size="18" /></div><div class="table-scroll"><table class="admin-table pricing-table"><thead><tr><th>Function</th><th>Provider cost USD</th><th>Charge tokens</th><th>Margin %</th><th>Active</th><th></th></tr></thead><tbody><tr v-for="item in pricing?.items || []" :key="item.feature_key"><td><strong>{{ item.label }}</strong><small>{{ item.feature_key }} · {{ item.unit }}</small></td><td><input v-model.number="item.provider_cost_usd" type="number" min="0" step="0.001"></td><td><input v-model.number="item.charge_tokens" type="number" min="0"></td><td><input v-model.number="item.margin_percent" type="number" step="0.1"></td><td><input v-model="item.is_active" type="checkbox"></td><td><button class="button button--small" @click="savePrice(item)"><Save :size="13" /> Save</button></td></tr></tbody></table></div></UiAppCard>
  </div>
</template>

<style scoped>.admin-lock{display:flex;align-items:center;gap:6px;padding:7px 9px;border-radius:8px;background:var(--primary-50);color:var(--primary-700);font-size:9px;font-weight:800}.admin-tabs{display:flex;gap:3px;margin:20px 0 12px;border-bottom:1px solid var(--border)}.admin-tabs button{padding:10px 13px;border-bottom:2px solid transparent;background:transparent;color:var(--muted);font-size:9px;font-weight:800}.admin-tabs button.active{border-color:var(--primary-600);color:var(--primary-700)}.admin-search{height:36px;padding:0 10px;border:1px solid var(--border);border-radius:9px}.table-scroll{overflow:auto}.admin-table{width:100%;border-collapse:collapse}.admin-table th,.admin-table td{padding:10px;border-bottom:1px solid var(--border);font-size:9px;text-align:left;white-space:nowrap}.admin-table th{color:var(--muted);font-size:8px;text-transform:uppercase}.admin-table td:first-child,.admin-table td:nth-child(2){display:grid;gap:2px}.admin-table small{color:var(--muted)}.inline-action{display:flex;gap:5px}.inline-action input,.pricing-table input[type=number]{width:95px;height:31px;padding:0 7px;border:1px solid var(--border);border-radius:7px}.admin-columns{display:grid;grid-template-columns:.8fr 1.2fr;gap:14px}.admin-form{display:grid;gap:11px}.admin-form label{display:grid;gap:5px;color:var(--muted);font-size:8px;font-weight:800;text-transform:uppercase}.admin-form input,.admin-form select{height:37px;padding:0 9px;border:1px solid var(--border);border-radius:8px}.created-code{padding:12px;border:1px solid var(--green);border-radius:9px;background:var(--green-soft);color:var(--green);font-family:monospace;font-weight:800;text-align:center}.promo-list{display:grid}.promo-list>div{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px 0;border-bottom:1px solid var(--border)}.promo-list span{display:grid;gap:2px}.promo-list strong{font-family:monospace;font-size:10px}.promo-list small{color:var(--muted);font-size:8px}@media(max-width:950px){.admin-columns{grid-template-columns:1fr}}</style>
