<script setup lang="ts">
import { Activity, BadgeDollarSign, TrendingUp, Users, WalletCards } from 'lucide-vue-next'
const { api } = useApi()
const { data: overview } = await useAsyncData('admin-overview', () => api<any>('/v1/platform-admin/overview'))
const retention = (days: 7 | 30) => overview.value?.retention?.[`day_${days}`] || { eligible: 0, retained: 0, rate_percent: null }
const usd = (cents: unknown) => `$${(Number(cents || 0) / 100).toFixed(2)}`
</script>

<template>
  <div>
    <UiPageHeader eyebrow="Internal operations" title="Platform analytics" description="Users, rolling retention, captured revenue and model-backed usage." />
    <div class="metric-grid admin-metrics">
      <UiAppCard class="metric-card"><div class="metric-card__head"><span class="metric-card__icon metric-card__icon--purple"><Users :size="17" /></span><span>Registered</span></div><strong>{{ overview?.users?.total || 0 }}</strong><small>+{{ overview?.users?.registered_30d || 0 }} in 30 days</small></UiAppCard>
      <UiAppCard class="metric-card"><div class="metric-card__head"><span class="metric-card__icon"><TrendingUp :size="17" /></span><span>D7 retention</span></div><strong>{{ retention(7).rate_percent == null ? '—' : `${retention(7).rate_percent}%` }}</strong><small>{{ retention(7).retained }} / {{ retention(7).eligible }} eligible</small></UiAppCard>
      <UiAppCard class="metric-card"><div class="metric-card__head"><span class="metric-card__icon"><Activity :size="17" /></span><span>D30 retention</span></div><strong>{{ retention(30).rate_percent == null ? '—' : `${retention(30).rate_percent}%` }}</strong><small>{{ retention(30).retained }} / {{ retention(30).eligible }} eligible</small></UiAppCard>
      <UiAppCard class="metric-card"><div class="metric-card__head"><span class="metric-card__icon metric-card__icon--green"><BadgeDollarSign :size="17" /></span><span>Deposited</span></div><strong>${{ Number(overview?.money?.deposited_usd || 0).toFixed(2) }}</strong><small>Captured PayPal + admin records</small></UiAppCard>
      <UiAppCard class="metric-card"><div class="metric-card__head"><span class="metric-card__icon"><WalletCards :size="17" /></span><span>AI usage</span></div><strong>{{ usd(overview?.balance?.spent) }}</strong><small>net of refunds</small></UiAppCard>
    </div>
    <div class="analytics-columns">
      <UiAppCard><div class="section-heading"><div><h2>Retention definition</h2><p>Rolling threshold, not exact calendar-day return</p></div><TrendingUp :size="18" /></div><div class="retention-list"><div><strong>D7</strong><span>Any authenticated activity on or after day 7</span><b>{{ retention(7).retained }} / {{ retention(7).eligible }}</b></div><div><strong>D30</strong><span>Any authenticated activity on or after day 30</span><b>{{ retention(30).retained }} / {{ retention(30).eligible }}</b></div></div></UiAppCard>
      <UiAppCard><div class="section-heading"><div><h2>Cash and provider costs</h2><p>Promo bonuses are not counted as revenue</p></div><BadgeDollarSign :size="18" /></div><div class="economics-list"><div><span>Deposited</span><strong>${{ Number(overview?.money?.deposited_usd || 0).toFixed(2) }}</strong></div><div><span>Provider cost</span><strong>${{ Number(overview?.money?.provider_cost_usd || 0).toFixed(2) }}</strong></div><div><span>Cash after provider cost</span><strong>${{ Number(overview?.money?.cash_after_provider_cost_usd || 0).toFixed(2) }}</strong></div></div></UiAppCard>
    </div>
    <UiAppCard class="usage-card"><div class="section-heading"><div><h2>Usage by function</h2><p>Customer dollars and provider cost grouped by price rule</p></div><Activity :size="18" /></div><div class="table-scroll"><table class="data-table"><thead><tr><th>Function</th><th>Provider / model</th><th>Operations</th><th>Customer spend</th><th>Provider cost</th></tr></thead><tbody><tr v-for="item in overview?.usage_by_feature || []" :key="item.feature_key"><td><strong>{{ item.label }}</strong><small>{{ item.feature_key }}</small></td><td><strong>{{ item.provider }}</strong><small>{{ item.model_id || '—' }}</small></td><td>{{ item.operations }}</td><td>{{ usd(item.cents_spent) }}</td><td>${{ Number(item.provider_cost_usd || 0).toFixed(2) }}</td></tr></tbody></table></div></UiAppCard>
  </div>
</template>

<style scoped>.admin-metrics{grid-template-columns:repeat(5,minmax(130px,1fr))}.analytics-columns{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.retention-list,.economics-list{display:grid;gap:9px}.retention-list>div{display:grid;grid-template-columns:45px 1fr auto;gap:10px;align-items:center;padding:10px;border:1px solid var(--border);border-radius:10px;font-size:9px}.retention-list span{color:var(--muted)}.economics-list>div{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid var(--border);font-size:10px}.usage-card{margin-top:14px}.table-scroll{overflow:auto}.data-table{width:100%;border-collapse:collapse}.data-table th,.data-table td{padding:10px;border-bottom:1px solid var(--border);text-align:left;font-size:9px}.data-table th{font-size:8px;color:var(--muted);text-transform:uppercase}.data-table td:first-child,.data-table td:nth-child(2){display:grid;gap:2px}.data-table small{color:var(--muted)}@media(max-width:1100px){.admin-metrics{grid-template-columns:repeat(2,1fr)}}@media(max-width:720px){.analytics-columns{grid-template-columns:1fr}}</style>
