<script setup lang="ts">
import { Copy, Gift, Power } from 'lucide-vue-next'
const { api } = useApi(); const { show } = useToast(); const createdCode = ref(''); const form = reactive({ code: '', bonus_usd: 5, bonus_percent: 0, max_redemptions: 1, expires_at: '' })
const { data: promos, refresh } = await useAsyncData('admin-promos', () => api<any>('/v1/platform-admin/promo-codes'))
async function createPromo() { try { const result = await api<any>('/v1/platform-admin/promo-codes', { method: 'POST', body: { code: form.code || null, kind: 'topup_bonus', bonus_cents: Math.round(Number(form.bonus_usd || 0) * 100), bonus_percent: Number(form.bonus_percent || 0), max_redemptions: Number(form.max_redemptions || 1), expires_at: form.expires_at ? new Date(form.expires_at).toISOString() : null } }); createdCode.value = result.code; await refresh(); show('Promo created', 'Copy it now; only the hash is stored.', 'success') } catch (error: any) { show('Could not create promo', error.message, 'error') } }
async function toggle(item: any) { await api(`/v1/platform-admin/promo-codes/${item.id}`, { method: 'PATCH', body: { is_active: !item.is_active } }); await refresh() }
async function copy() { await navigator.clipboard.writeText(createdCode.value); show('Copied', createdCode.value, 'success') }
</script>
<template><div><UiPageHeader eyebrow="Growth" title="Top-up promo codes" description="Fixed and percentage bonuses applied only after a successful PayPal top-up." /><div class="promo-grid"><UiAppCard><div class="section-heading"><div><h2>Create promo</h2><p>At least one bonus must be greater than zero</p></div><Gift :size="18" /></div><form class="promo-form" @submit.prevent="createPromo"><label>Custom code <small>optional</small><input v-model="form.code" placeholder="FRAME-2026"></label><label>Fixed bonus, USD<input v-model.number="form.bonus_usd" type="number" min="0" step="0.01"></label><label>Bonus, %<input v-model.number="form.bonus_percent" type="number" min="0" max="500" step="0.1"></label><label>Maximum uses<input v-model.number="form.max_redemptions" type="number" min="1"></label><label>Expires <small>optional</small><input v-model="form.expires_at" type="datetime-local"></label><button class="button button--primary" type="submit">Create promo</button></form><button v-if="createdCode" class="created-code" @click="copy"><code>{{ createdCode }}</code><Copy :size="15" /></button></UiAppCard><UiAppCard><div class="section-heading"><div><h2>Issued promos</h2><p>Stored prefixes and redemption counters</p></div></div><div class="promo-list"><div v-for="item in promos?.items || []" :key="item.id"><span><strong>{{ item.code }}</strong><small>${{ (Number(item.bonus_cents || 0)/100).toFixed(2) }} + {{ Number(item.bonus_percent || 0).toFixed(1) }}% · {{ item.redemption_count }}/{{ item.max_redemptions || '∞' }}</small></span><button :class="{ off: !item.is_active }" @click="toggle(item)"><Power :size="15" />{{ item.is_active ? 'Active' : 'Disabled' }}</button></div></div></UiAppCard></div></div></template>
<style scoped>.promo-grid{display:grid;grid-template-columns:.8fr 1.2fr;gap:14px}.promo-form{display:grid;grid-template-columns:1fr 1fr;gap:10px}.promo-form label{display:grid;gap:5px;font-size:8px;font-weight:800}.promo-form label:first-child,.promo-form button{grid-column:1/-1}.promo-form small{color:var(--muted)}.promo-form input{border:1px solid var(--border);border-radius:9px;padding:10px;font-size:10px}.created-code{width:100%;margin-top:12px;display:flex;justify-content:space-between;padding:12px;border:1px solid #c988d3;background:#fbf2fd;border-radius:10px}.promo-list{display:grid}.promo-list>div{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:11px 0;border-bottom:1px solid var(--border)}.promo-list span{display:grid;gap:3px}.promo-list strong{font-family:monospace;font-size:10px}.promo-list small{font-size:8px;color:var(--muted)}.promo-list button{display:flex;align-items:center;gap:5px;border:0;background:#eaf7ef;color:#18743c;border-radius:8px;padding:7px;font-size:8px}.promo-list button.off{background:#f3f0f3;color:#776f79}@media(max-width:800px){.promo-grid{grid-template-columns:1fr}}</style>
