<script setup lang="ts">
import { Search, WalletCards } from 'lucide-vue-next'
const { api } = useApi(); const { show } = useToast(); const query = ref(''); const adjustments = reactive<Record<string, number>>({}); const deposits = reactive<Record<string, number>>({})
const { data: users, refresh } = await useAsyncData('admin-users', () => api<any>('/v1/platform-admin/users'))
const filtered = computed(() => (users.value?.items || []).filter((item: any) => `${item.email} ${item.display_name} ${item.organization_name}`.toLowerCase().includes(query.value.toLowerCase())))
const money = (cents: unknown) => `$${(Number(cents || 0) / 100).toFixed(2)}`
async function setStatus(item: any, status: string) { await api(`/v1/platform-admin/users/${item.id}`, { method: 'PATCH', body: { status } }); await refresh(); show('User updated', `${item.email} is now ${status}.`, 'success') }
async function adjust(item: any) { const amount = Number(adjustments[item.id] || 0); if (!amount) return; await api(`/v1/platform-admin/users/${item.id}/credits`, { method: 'POST', body: { amount_cents: Math.round(amount * 100), deposited_usd: amount > 0 && Number(deposits[item.id] || 0) > 0 ? Number(deposits[item.id]) : null, description: 'Manual platform admin balance adjustment' } }); adjustments[item.id] = 0; deposits[item.id] = 0; await refresh(); show('Balance updated', `${amount > 0 ? '+' : ''}$${amount.toFixed(2)}`, 'success') }
</script>
<template><div><UiPageHeader eyebrow="Customers" title="Users & balances" description="Account state, activity, deposits, usage and manual dollar adjustments." /><div class="admin-search"><Search :size="16" /><input v-model="query" placeholder="Search by name, email or organization" aria-label="Search users"></div><UiAppCard><div class="table-scroll"><table class="data-table"><thead><tr><th>User</th><th>Workspace</th><th>Balance</th><th>Deposited / used</th><th>Status</th><th>Adjust USD</th></tr></thead><tbody><tr v-for="item in filtered" :key="item.id"><td><strong>{{ item.display_name }}</strong><small>{{ item.email }}</small></td><td><strong>{{ item.organization_name || '—' }}</strong><small>{{ item.role || '—' }}</small></td><td><b>{{ money(item.balance_cents) }}</b></td><td><strong>${{ Number(item.deposited_usd || 0).toFixed(2) }}</strong><small>{{ money(item.cents_spent) }} used</small></td><td><select :value="item.status" @change="setStatus(item, ($event.target as HTMLSelectElement).value)"><option value="active">active</option><option value="blocked">blocked</option><option value="pending_verification">pending</option></select></td><td><div class="adjust"><input v-model.number="adjustments[item.id]" type="number" step="0.01" placeholder="± USD" :aria-label="`Adjust ${item.email}`"><input v-model.number="deposits[item.id]" type="number" step="0.01" placeholder="cash paid"><button class="button button--small" @click="adjust(item)"><WalletCards :size="14" /> Apply</button></div></td></tr></tbody></table></div></UiAppCard></div></template>
<style scoped>.admin-search{height:42px;max-width:460px;display:flex;align-items:center;gap:8px;border:1px solid var(--border);background:#fff;border-radius:11px;padding:0 12px;margin-bottom:14px}.admin-search input{border:0;outline:0;flex:1;font-size:10px}.table-scroll{overflow:auto}.data-table{width:100%;border-collapse:collapse}.data-table th,.data-table td{padding:10px;border-bottom:1px solid var(--border);text-align:left;font-size:9px;vertical-align:top}.data-table th{font-size:8px;color:var(--muted);text-transform:uppercase}.data-table td:first-child,.data-table td:nth-child(2),.data-table td:nth-child(4){display:grid;gap:2px}.data-table small{color:var(--muted)}select,input{border:1px solid var(--border);border-radius:8px;padding:7px;font-size:9px}.adjust{display:grid;grid-template-columns:75px 75px auto;gap:5px;min-width:250px}</style>
