<script setup lang="ts">
import { BarChart3, Eye, Heart, MousePointerClick, Share2, TrendingUp } from 'lucide-vue-next'
const { api, projectId } = useApi()
const { data } = await useAsyncData('analytics', () => api<any>(`/v1/projects/${projectId.value}/analytics/summary`), { default:()=>({kpis:{},latest_metrics:[],patterns:[]}) })
const metric = computed(()=>data.value.latest_metrics?.[0]?.metrics || {})
const chart=[42,58,49,73,66,81,76,88,82,94,89,97]
</script>
<template><div><UiPageHeader eyebrow="Normalized evidence" title="Analytics" description="Raw provider values remain intact; comparisons happen only inside relevant platform, account, format and age cohorts."><button class="button">Last 28 days</button><button class="button button--primary">Weekly intelligence</button></UiPageHeader><div class="metric-grid"><UiAppCard class="metric-card"><span class="metric-card__icon"><Eye :size="18" /></span><span class="metric-card__label">Views</span><div class="metric-card__value"><strong>{{ metric.views || 0 }}</strong><span>Demo cohort</span></div></UiAppCard><UiAppCard class="metric-card"><span class="metric-card__icon"><Heart :size="18" /></span><span class="metric-card__label">Likes</span><div class="metric-card__value"><strong>{{ metric.likes || 0 }}</strong><span>Normalized</span></div></UiAppCard><UiAppCard class="metric-card"><span class="metric-card__icon"><Share2 :size="18" /></span><span class="metric-card__label">Shares</span><div class="metric-card__value"><strong>{{ metric.shares || 0 }}</strong><span>High intent</span></div></UiAppCard><UiAppCard class="metric-card"><span class="metric-card__icon"><TrendingUp :size="18" /></span><span class="metric-card__label">Avg. viewed</span><div class="metric-card__value"><strong>{{ metric.average_view_percentage || 0 }}%</strong><span>YouTube only</span></div></UiAppCard></div><div class="grid-two analytics-layout"><UiAppCard><div class="section-heading"><div><h2>Observed performance</h2><p>Percentile against the relevant cohort</p></div><BarChart3 :size="18" /></div><div class="chart"><span v-for="(value,index) in chart" :key="index" :style="{height:`${value}%`}" /></div><div class="chart-labels"><span>Jul 20</span><span>Jul 27</span><span>Aug 3</span><span>Aug 9</span></div></UiAppCard><UiAppCard><div class="section-heading"><div><h2>Pattern evidence</h2><p>Correlation is not presented as causation</p></div><MousePointerClick :size="18" /></div><div class="pattern-list"><article v-for="pattern in data.patterns" :key="pattern.name"><div><strong>{{ pattern.name }}</strong><span>n={{ pattern.sample_size }} · {{ Math.round(pattern.confidence*100) }}% confidence</span></div><strong>+{{ pattern.delta_percentile }}</strong></article></div><div class="analytics-note">{{ data.provider_comparison_warning }}</div></UiAppCard></div></div></template>
<style scoped>.analytics-layout{margin-top:15px;align-items:stretch}.chart{display:flex;height:230px;align-items:flex-end;gap:9px;padding:20px 5px 0;border-bottom:1px solid var(--border);background:linear-gradient(180deg,transparent 24%,var(--border) 25%,transparent 26%,transparent 49%,var(--border) 50%,transparent 51%,transparent 74%,var(--border) 75%,transparent 76%)}.chart span{flex:1;border-radius:5px 5px 1px 1px;background:linear-gradient(180deg,var(--primary-400),var(--primary-700));opacity:.82}.chart-labels{display:flex;justify-content:space-between;margin-top:7px;color:var(--muted);font-size:8px}.pattern-list{display:grid}.pattern-list article{display:flex;align-items:center;justify-content:space-between;padding:12px 0;border-bottom:1px solid var(--border)}.pattern-list article>div{display:grid;gap:2px}.pattern-list strong{font-size:10px}.pattern-list span{color:var(--muted);font-size:8px}.pattern-list article>strong{color:var(--green)}.analytics-note{margin-top:14px;padding:10px;border-radius:9px;background:var(--blue-soft);color:var(--blue);font-size:8px;line-height:1.5}</style>

