<script setup lang="ts">
import { ChevronLeft, ChevronRight, CircleAlert, Plus } from 'lucide-vue-next'
const { api, projectId } = useApi()
const { data } = await useAsyncData('calendar', () => api<any>(`/v1/projects/${projectId.value}/calendar`), { default: () => ({ items: [], timezone: 'America/New_York' }) })
const days = ['Mon 10', 'Tue 11', 'Wed 12', 'Thu 13', 'Fri 14', 'Sat 15', 'Sun 16']
const itemsFor = (index: number) => (data.value.items || []).filter((_: any, itemIndex: number) => itemIndex % 7 === index)
</script>
<template><div><UiPageHeader eyebrow="Cadence" title="Calendar" description="Research, generation, approvals, publications and metric checkpoints share one timezone-aware plan."><button class="button"><ChevronLeft :size="14" /></button><button class="button">Aug 10–16</button><button class="button"><ChevronRight :size="14" /></button><button class="button button--primary"><Plus :size="15" /> Plan content</button></UiPageHeader><div class="cadence-warning"><CircleAlert :size="16" /><div><strong>Cadence protected</strong><span>At least 18 hours between YouTube posts · maximum 3 per week</span></div><small>{{ data.timezone }}</small></div><UiAppCard :padded="false" class="calendar-shell"><div class="calendar-grid"><section v-for="(day,index) in days" :key="day"><header>{{ day }}</header><div class="calendar-cell"><article v-for="item in itemsFor(index)" :key="item.id" :class="`calendar-item calendar-item--${item.kind}`"><span>{{ item.kind?.replaceAll('_',' ') }}</span><strong>{{ item.title || item.objective || item.window || 'Scheduled work' }}</strong><small>{{ item.status }}</small></article><button class="calendar-add"><Plus :size="14" /></button></div></section></div></UiAppCard><div class="calendar-legend"><span><i class="purple" /> Ideas</span><span><i class="blue" /> Research</span><span><i class="amber" /> Approval</span><span><i class="green" /> Publication / metrics</span></div></div></template>
<style scoped>.cadence-warning{display:flex;align-items:center;gap:9px;margin-bottom:13px;padding:10px 12px;border:1px solid #ecdcae;border-radius:10px;background:var(--amber-soft);color:#9a680a}.cadence-warning div{display:grid;flex:1;gap:1px}.cadence-warning strong{font-size:9px}.cadence-warning span,.cadence-warning small{font-size:8px}.calendar-shell{overflow-x:auto}.calendar-grid{display:grid;min-width:850px;grid-template-columns:repeat(7,1fr)}.calendar-grid>section{border-right:1px solid var(--border)}.calendar-grid>section:last-child{border:0}.calendar-grid header{padding:11px;border-bottom:1px solid var(--border);color:var(--muted);font-size:9px;font-weight:800;text-align:center;text-transform:uppercase}.calendar-cell{min-height:430px;padding:8px}.calendar-item{display:grid;gap:3px;margin-bottom:7px;padding:9px;border-left:3px solid var(--primary-500);border-radius:7px;background:var(--primary-50)}.calendar-item span{color:var(--primary-700);font-size:7px;text-transform:uppercase}.calendar-item strong{font-size:9px;line-height:1.35}.calendar-item small{color:var(--muted);font-size:7px}.calendar-item--research_run{border-color:var(--blue);background:var(--blue-soft)}.calendar-item--publication,.calendar-item--metric_checkpoint{border-color:var(--green);background:var(--green-soft)}.calendar-item--generation_job{border-color:var(--amber);background:var(--amber-soft)}.calendar-add{display:grid;width:100%;height:30px;place-items:center;border:1px dashed var(--border);border-radius:7px;background:transparent;color:var(--muted)}.calendar-legend{display:flex;flex-wrap:wrap;gap:15px;margin-top:11px;color:var(--muted);font-size:8px}.calendar-legend span{display:flex;align-items:center;gap:5px}.calendar-legend i{width:7px;height:7px;border-radius:2px;background:var(--primary-500)}.calendar-legend .blue{background:var(--blue)}.calendar-legend .amber{background:var(--amber)}.calendar-legend .green{background:var(--green)}</style>
