<script setup lang="ts">
import { Download, Film, Grid2X2, Image, List, Music2, Search } from 'lucide-vue-next'
const { api, projectId, apiBase } = useApi()
const { data } = await useAsyncData('library-videos', () => api<any>(`/v1/projects/${projectId.value}/videos`), { default: () => ({ items: [] }) })
const assets = computed(() => (data.value.items || []).flatMap((video: any) => (video.versions || []).map((version: any) => ({ ...version, title: video.title, videoStatus: video.status }))))
</script>
<template><div><UiPageHeader eyebrow="Media provenance" title="Library" description="Final videos, thumbnails, audio, scenes and owned assets with rights status and checksums."><button class="button"><List :size="14" /> List</button><button class="button button--primary"><Grid2X2 :size="14" /> Grid</button></UiPageHeader><div class="library-tabs"><button class="active"><Film :size="14" /> Videos</button><button><Image :size="14" /> Images</button><button><Music2 :size="14" /> Audio</button><div><Search :size="14" /><span>Search assets…</span></div></div><div v-if="assets.length" class="asset-grid"><UiAppCard v-for="asset in assets" :key="asset.id" :padded="false" class="asset-card"><div class="asset-card__preview"><video :src="`${apiBase}${asset.render_url}`" preload="metadata" muted /><span>{{ asset.aspect_ratio }}</span></div><div class="asset-card__body"><strong>{{ asset.title }}</strong><small>{{ Math.round(asset.duration_ms/1000) }} sec · H.264 · owned</small><div><UiStatusBadge :status="asset.videoStatus" /><a :href="`${apiBase}${asset.render_url}`" download class="icon-button"><Download :size="14" /></a></div></div></UiAppCard></div><UiAppCard v-else><div class="empty-state"><div><span class="empty-state__icon"><Film :size="23" /></span><h3>No media assets yet</h3><p>Completed productions will appear here with provenance, rights status, render manifests and checksums.</p><NuxtLink to="/ideas" class="button button--primary">Start production</NuxtLink></div></div></UiAppCard></div></template>
<style scoped>.library-tabs{display:flex;align-items:center;gap:5px;margin-bottom:14px}.library-tabs>button{display:flex;align-items:center;gap:5px;padding:7px 9px;border-radius:8px;background:transparent;color:var(--muted);font-size:9px}.library-tabs>button.active{background:var(--primary-100);color:var(--primary-700);font-weight:800}.library-tabs>div{display:flex;align-items:center;gap:6px;margin-left:auto;padding:7px 9px;border:1px solid var(--border);border-radius:8px;background:white;color:var(--muted);font-size:9px}.asset-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.asset-card{overflow:hidden}.asset-card__preview{position:relative;display:grid;height:190px;place-items:center;overflow:hidden;background:#15101a}.asset-card__preview video{width:100%;height:100%;object-fit:contain}.asset-card__preview span{position:absolute;top:8px;left:8px;padding:4px 6px;border-radius:6px;background:rgb(0 0 0 / 58%);color:white;font-size:8px}.asset-card__body{display:grid;gap:3px;padding:12px}.asset-card__body>strong{overflow:hidden;font-size:10px;text-overflow:ellipsis;white-space:nowrap}.asset-card__body>small{color:var(--muted);font-size:8px}.asset-card__body>div{display:flex;align-items:center;justify-content:space-between;margin-top:7px}@media(max-width:1050px){.asset-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.asset-grid{grid-template-columns:1fr}}</style>

