<script setup lang="ts">
import { Download, Film, Grid2X2, List, Search, Send } from 'lucide-vue-next'
const { api, projectId, apiBase } = useApi()
const view = ref<'grid' | 'list'>('grid')
const search = ref('')
const { data } = await useAsyncData(
  () => `library-videos-${projectId.value}`,
  () => api<any>(`/v1/projects/${projectId.value}/videos`),
  {
    default: () => ({ items: [] }),
    lazy: true,
    server: false,
    watch: [projectId],
  },
)
const assets = computed(() => (data.value.items || []).flatMap((video: any) => (video.versions || []).map((version: any) => ({ ...version, title: video.title, videoStatus: video.status }))).filter((asset: any) => asset.title?.toLowerCase().includes(search.value.trim().toLowerCase())))
</script>
<template><div><UiPageHeader eyebrow="Media provenance" title="Library" description="Final video versions with rights status, render manifests and checksums."><button class="button" :class="{'button--primary':view==='list'}" @click="view='list'"><List :size="14" /> List</button><button class="button" :class="{'button--primary':view==='grid'}" @click="view='grid'"><Grid2X2 :size="14" /> Grid</button></UiPageHeader><div class="library-toolbar"><span><Film :size="14" /> Video versions</span><label><Search :size="14" /><input v-model="search" aria-label="Search video assets" placeholder="Search assets…"></label></div><div v-if="assets.length" class="asset-grid" :class="{'asset-grid--list':view==='list'}"><UiAppCard v-for="asset in assets" :key="asset.id" :padded="false" class="asset-card"><div class="asset-card__preview"><video :src="`${apiBase}${asset.render_url}`" preload="metadata" muted controls /><span>{{ asset.aspect_ratio }}</span></div><div class="asset-card__body"><strong>{{ asset.title }}</strong><small>{{ Math.round(asset.duration_ms/1000) }} sec · H.264 · owned</small><div><UiStatusBadge :status="asset.status || asset.videoStatus" /><span class="asset-actions"><NuxtLink :to="`/publishing?version=${encodeURIComponent(asset.id)}`" class="icon-button" aria-label="Send video to publication" title="Send to publication"><Send :size="14" /></NuxtLink><a :href="`${apiBase}${asset.render_url}`" download class="icon-button" aria-label="Download video"><Download :size="14" /></a></span></div></div></UiAppCard></div><UiAppCard v-else><div class="empty-state"><div><span class="empty-state__icon"><Film :size="23" /></span><h3>{{ search ? 'No matching video assets' : 'No media assets yet' }}</h3><p>Completed productions will appear here with provenance, rights status, render manifests and checksums.</p><NuxtLink to="/ideas" class="button button--primary">Start production</NuxtLink></div></div></UiAppCard></div></template>
<style scoped>.library-toolbar{display:flex;align-items:center;gap:8px;margin-bottom:14px}.library-toolbar>span,.library-toolbar>label{display:flex;align-items:center;gap:6px;padding:7px 9px;border:1px solid var(--border);border-radius:8px;background:white;color:var(--muted);font-size:9px}.library-toolbar>label{margin-left:auto}.library-toolbar input{border:0;outline:0}.asset-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.asset-grid--list{grid-template-columns:1fr}.asset-grid--list .asset-card{display:grid;grid-template-columns:220px 1fr}.asset-grid--list .asset-card__preview{height:130px}.asset-card{overflow:hidden}.asset-card__preview{position:relative;display:grid;height:190px;place-items:center;overflow:hidden;background:#15101a}.asset-card__preview video{width:100%;height:100%;object-fit:contain}.asset-card__preview span{position:absolute;top:8px;left:8px;padding:4px 6px;border-radius:6px;background:rgb(0 0 0 / 58%);color:white;font-size:8px}.asset-card__body{display:grid;gap:3px;padding:12px}.asset-card__body>strong{overflow:hidden;font-size:10px;text-overflow:ellipsis;white-space:nowrap}.asset-card__body>small{color:var(--muted);font-size:8px}.asset-card__body>div{display:flex;align-items:center;justify-content:space-between;margin-top:7px}.asset-actions{display:flex;gap:5px}@media(max-width:1050px){.asset-grid{grid-template-columns:repeat(2,1fr)}.asset-grid--list{grid-template-columns:1fr}}@media(max-width:560px){.asset-grid{grid-template-columns:1fr}.asset-grid--list .asset-card{grid-template-columns:1fr}}</style>
